application: keybindviewer
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /css
  static_dir: html/css

- url: /js
  static_dir: html/js

- url: /img
  static_dir: html/img

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /about
  script: view.py

- url: /v.*
  script: view.py

- url: /.*
  script: view.py
