# Autogeneraged by actionfilter_lua_to_py.pl from ActionFilter.lua

ActionFilterEncodeList = {
'0' : "Target Pet",
'1' : "Target Talker",
'2' : "Target Focus",
'3' : "Strafe Right",
'4' : "Game Menu",
'5' : "Target Party Pet 2",
'6' : "Assist Target",
'7' : "Run",
'8' : "Target Party Pet 1",
'9' : "Target Last Hostile",
'10' : "Target Party Member 2",
'11' : "Target Party Pet 3",
'12' : "Auto Run",
'13' : "Turn Right",
'14' : "Stop Attack",
'15' : "Target Party Member 1",
'16' : "Target Nearest Friendly Player",
'17' : "Strafe Left",
'18' : "Target Party Member 3",
'19' : "Target Previous Friendly Player",
'20' : "Forward",
'21' : "Dismount",
'22' : "Sit/Stand",
'23' : "Start Attack",
'24' : "Target Self",
'25' : "Turn Left",
'26' : "Set Focus Target",
'27' : "Screenshot",
'28' : "Backpedal",
'29' : "Target Mouseover",
'30' : "Stop Casting",
'31' : "Jump",
'32' : "Target Nearest Enemy",
'33' : "Target Previous Friend",
'34' : "Attack Target",
'35' : "Target Last Target",
}
